#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  local launcher=""
  if   command -v wslview     >/dev/null 2>&1; then launcher="wslview"
  elif command -v explorer.exe >/dev/null 2>&1; then launcher="explorer.exe"
  elif command -v xdg-open    >/dev/null 2>&1; then launcher="xdg-open"
  elif command -v open        >/dev/null 2>&1; then launcher="open"
  fi
  if [[ -n "$launcher" ]]; then
    "$launcher" "$url" >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
  else
    warn "couldn't open a browser — visit it manually: $url"
  fi
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — fix the SFL GitHub App installation permissions so the
# "AI review auto-merge" workflow can mint its token.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=3

REPO="HemSoft/hs-buddy"
INSTALLATION_ID="150383874"

banner "SFL App permissions — fix AI review auto-merge"

# ── Stage 1: grant the missing permissions on the installation ────────────
stage "Grant permissions on the SFL app registration"
say "The 'AI review auto-merge' workflow fails at its first step:"
say "  HTTP 422 — 'The level of access for permissions requested are not"
say "  granted to this installation.' It asks the SFL app for contents:write,"
say "  checks:write, pull-requests:write and issues:read."
say ""
step "Open the app registration's 'Permissions & events' page first —"
step "the installation page cannot grant a permission the app does not request:"
open_url "https://github.com/organizations/HemSoft/settings/apps/sfl-app/permissions"
pause "If that page 404s, the app is user-owned: open https://github.com/settings/apps/sfl-app/permissions instead. Enter = continue"
say ""
say "Under 'Permissions & events', set 'Contents' to: Read and write"
say "(Checks, Pull requests and Issues may already be correct:"
say "    Checks ........... Read and write"
say "    Pull requests .... Read and write"
say "    Issues ........... Read)"
step "Click 'Save' on the registration page."
pause "Press Enter once you've saved the permission changes"
say ""
step "Now open the installation's Configure page to approve the pending change:"
open_url "https://github.com/organizations/HemSoft/settings/installations/${INSTALLATION_ID}"
pause "Did that page open and show the sfl-app Configure screen? [Enter = yes; if 404, press Enter anyway]"
say ""
if ! confirm "Is the sfl-app configuration page open?"; then
  say "Trying your personal settings instead (works if a user owns the app):"
  open_url "https://github.com/settings/installations/${INSTALLATION_ID}"
  pause "Press Enter once the configuration page is open"
fi
say ""
step "On the installation Configure page, confirm the upgraded permissions are active:"
say "    Contents ......... Read and write"
say "    Checks ........... Read and write"
say "    Pull requests .... Read and write"
say "    Issues ........... Read"
pause "Press Enter once you've verified the installation permissions"

# ── Stage 2: approve pending permission changes if prompted ───────────────
stage "Approve pending permission change (only if the app is user-owned)"
say "If the SFL app is owned by a user (not the org), GitHub may queue the"
say "new permissions for org approval instead of applying them instantly."
say ""
open_url "https://github.com/organizations/HemSoft/settings/installations"
step "Look for 'sfl-app' with a 'Pending review' / 'Permissions requested' notice."
step "If present, open it and click 'Review request' → 'Grant access'."
say ""
if confirm "Was there a pending permission request that you just approved?"; then
  say "Good — permissions are now active."
else
  say "No pending request — changes applied directly. Moving on."
fi

# ── Stage 3: verify the controller works, strictly read-only ─────────────
stage "Verify — run the controller locally in evaluation mode"
step "Verify the active GitHub account is HemSoft before any gh call:"
if ! gh auth status 2>&1 | grep -E "Logged in to github.com account HemSoft" >/dev/null; then
  warn "The active github.com account is not HemSoft (gh auth status)."
  say "Switch first: gh auth switch --user HemSoft, then re-run this wizard."
  exit 1
fi
ACTIVE=$(gh api user --jq .login) || { warn "gh api user failed."; exit 1; }
say "Active account: $ACTIVE"
say ""
say "This runs the controller WITHOUT --apply and with the CLI's user token:"
say "it exercises the reconcile logic but NOT the SFL App token mint — the"
say "original HTTP 422 was the App token, and only the scheduled workflow run"
say "mints App tokens. After the permissions land, watch the next 'AI review"
say "auto-merge' run in the Actions tab for the definitive verdict."
if confirm "Run the controller in evaluation mode now?"; then
  if GH_TOKEN="$(gh auth token)" bun scripts/run-ai-review-automerge.ts; then
    say "Controller evaluation completed cleanly (user-token path)."
    say "Next: check the next scheduled 'AI review auto-merge' run in the"
    say "Actions tab — its token-mint step is the real app-credential test."
  else
    warn "Controller evaluation failed — see the output above."
    warn "If it is the HTTP 422, re-run this wizard after re-checking the permissions."
  fi
else
  note "Skipped verification. Later: bun scripts/run-ai-review-automerge.ts (no --apply)"
fi
# ──────────────────────────────────────────────────────────────────────────

finish
