import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'

/** Exclusive creation cannot overwrite a bundle that appears concurrently. */
export function createE18ePlaceholder(filePath: string): boolean {
  mkdirSync(dirname(filePath), { recursive: true })
  try {
    writeFileSync(
      filePath,
      [
        '// Temporary e18e analysis placeholder.',
        '// The real Electron main bundle is generated by vite-plugin-electron during build.',
        '',
      ].join('\n'),
      { flag: 'wx' }
    )
    return true
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === 'EEXIST') return false
    throw error
  }
}
