import { existsSync, mkdirSync, rmSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import { spawnSync } from 'node:child_process'

const electronMain = 'dist-electron/main.js'
const createdPlaceholder = !existsSync(electronMain)
const documentedDirectExceptions = new Set([
  '@types/node',
  'esbuild',
  'typescript',
  'vscode-jsonrpc',
])
const ansiPattern = new RegExp(`${String.fromCharCode(27)}\\[[0-9;]*m`, 'g')

interface E18eMessage {
  message: string
  severity: 'debug' | 'info' | 'warning' | 'error'
}

interface E18eReport {
  stats?: {
    extraStats?: Array<{ name: string; value: number }>
  }
  messages?: E18eMessage[]
}

function stripAnsi(value: string): string {
  return value.replace(ansiPattern, '')
}

function duplicatePackageName(message: string): string | undefined {
  return /^\[duplicate dependency\] (?<name>\S+) has /u.exec(message)?.groups?.name
}

function formatPackageList(packages: string[]): string {
  return packages.length > 0 ? packages.join(', ') : 'none'
}

if (createdPlaceholder) {
  mkdirSync(dirname(electronMain), { recursive: true })
  writeFileSync(
    electronMain,
    [
      '// Temporary e18e analysis placeholder.',
      '// The real Electron main bundle is generated by vite-plugin-electron during build.',
      '',
    ].join('\n')
  )
}

try {
  const result = spawnSync(
    'bun',
    [
      'x',
      '--yes',
      '@e18e/cli',
      'analyze',
      '--log-level',
      'error',
      '--report-level',
      'warn',
      '--json',
    ],
    { encoding: 'utf8', shell: process.platform === 'win32' }
  )

  if (result.error) {
    throw result.error
  }

  if (result.stderr) {
    process.stderr.write(result.stderr)
  }

  const report = JSON.parse(result.stdout) as E18eReport
  const messages = report.messages ?? []
  const errors = messages.filter(message => message.severity === 'error')
  const warnings = messages.filter(message => message.severity === 'warning')
  const duplicateCount =
    report.stats?.extraStats?.find(stat => stat.name === 'duplicateDependencyCount')?.value ??
    warnings.length
  const directDuplicates = warnings
    .map(message => stripAnsi(message.message))
    .filter(message => message.includes('root@'))
    .map(duplicatePackageName)
    .filter((name): name is string => Boolean(name))

  const undocumentedDirectDuplicates = directDuplicates.filter(
    name => !documentedDirectExceptions.has(name)
  )

  console.log(`e18e duplicate dependency count: ${duplicateCount}`)
  console.log(`e18e warnings: ${warnings.length}`)
  console.log(`documented direct dependency exceptions: ${formatPackageList(directDuplicates)}`)
  console.log(
    `undocumented direct dependency findings: ${formatPackageList(undocumentedDirectDuplicates)}`
  )

  for (const error of errors) {
    console.error(stripAnsi(error.message))
  }

  process.exitCode = errors.length > 0 || undocumentedDirectDuplicates.length > 0 ? 1 : 0
} finally {
  if (createdPlaceholder) {
    rmSync(electronMain, { force: true })
  }
}
