name: Test SFL Reusable Call

on:
  workflow_dispatch:
    inputs:
      issue-number:
        description: Issue to test
        required: true
        type: string

jobs:
  test-implement:
    uses: ./.github/workflows/sfl-implement.lock.yml
    with:
      issue-number: ${{ github.event.inputs.issue-number }}
    secrets: inherit
